"""changes

Revision ID: 588b23f93741
Revises: 7f58ce3b111e
Create Date: 2025-02-11 21:23:00.759130

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '588b23f93741'
down_revision: Union[str, None] = '7f58ce3b111e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_Flashcard_id', table_name='Flashcard')
    op.drop_table('Flashcard')
    op.drop_index('ix_User_id', table_name='User')
    op.drop_table('User')
    op.drop_index('ix_CodingFlashcard_id', table_name='CodingFlashcard')
    op.drop_table('CodingFlashcard')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('CodingFlashcard',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('question', sa.VARCHAR(), nullable=False),
    sa.Column('category', sa.VARCHAR(), nullable=False),
    sa.Column('solution', sa.VARCHAR(), nullable=False),
    sa.Column('difficult', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category'),
    sa.UniqueConstraint('question')
    )
    op.create_index('ix_CodingFlashcard_id', 'CodingFlashcard', ['id'], unique=False)
    op.create_table('User',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('email', sa.VARCHAR(), nullable=False),
    sa.Column('hashed_password', sa.VARCHAR(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('last_name', sa.VARCHAR(), nullable=True),
    sa.Column('level', sa.VARCHAR(), nullable=True),
    sa.Column('profile_image', sa.VARCHAR(), nullable=True),
    sa.Column('good_answers', sa.INTEGER(), nullable=True),
    sa.Column('regular_answers', sa.INTEGER(), nullable=True),
    sa.Column('bad_answers', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index('ix_User_id', 'User', ['id'], unique=False)
    op.create_table('Flashcard',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('question', sa.VARCHAR(), nullable=False),
    sa.Column('category', sa.VARCHAR(), nullable=False),
    sa.Column('solution', sa.VARCHAR(), nullable=False),
    sa.Column('difficult', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('question')
    )
    op.create_index('ix_Flashcard_id', 'Flashcard', ['id'], unique=False)
    # ### end Alembic commands ###
